apiVersion: v1
kind: Service
metadata:
  name: werweruser-service
spec:
  selector:
    app: werweruser
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      nodePort: 30009
  type: NodePort
