apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwUser-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wwUser
  strategy:
    rollingUpdate: 
      maxSurge: 50% 
      maxUnavailable: 10%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: wwUser
    spec:
      containers:
      - name: wwUser
        image: qiuer0121/wwUser:latest
        ports:
        - containerPort: 9095
        resources: 
          limits: 
            cpu: 800m 
            memory: 5Gi 
          requests:  
            cpu: 50m
            memory: 100Mi

